package View;

import Control.ClienteCtl;
import Control.CotizacionCtl;
import java.sql.Date;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public class JDRegistrar_Cotizacion extends javax.swing.JDialog {
    ClienteCtl objClienteCtl = new ClienteCtl();
    CotizacionCtl objCotizacionCtl = new CotizacionCtl();
    int idcotizacion, idcliente;
    public JDRegistrar_Cotizacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Registrar Cotización");
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNumero_Identifica = new javax.swing.JTextField();
        txtNombre_Cliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNomb_Trabajo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNumeroCotiza = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jdateFecha = new com.toedter.calendar.JDateChooser();
        btnBuscar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnGrabar = new javax.swing.JButton();
        btnRegreso = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCantEstampado = new javax.swing.JTextField();
        txtValorEstampado = new javax.swing.JTextField();
        txtSubtestampado = new javax.swing.JTextField();
        txtCantCosido = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtValorCosido = new javax.swing.JTextField();
        txtSubtcosido = new javax.swing.JTextField();
        txtCantEmblocado = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtValorEmblocado = new javax.swing.JTextField();
        txtSubtemblocado = new javax.swing.JTextField();
        txtCantTransporte = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtValorTransporte = new javax.swing.JTextField();
        txtSubttransporte = new javax.swing.JTextField();
        txtCantOtros = new javax.swing.JTextField();
        txtCantTerminado = new javax.swing.JTextField();
        cbxTerminado = new javax.swing.JComboBox();
        txtValorTerminado = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtValorOtros = new javax.swing.JTextField();
        txtSubtotros = new javax.swing.JTextField();
        txtSubtterminado = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtUtilidad = new javax.swing.JTextField();
        txtSubtotal = new javax.swing.JTextField();
        txtValorUtilidad = new javax.swing.JTextField();
        txtValorTrabajo = new javax.swing.JTextField();
        txtCantPlegado = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtValorPlegado = new javax.swing.JTextField();
        txtSubtplegado = new javax.swing.JTextField();
        txtCantEmpacado = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtValorEmpacado = new javax.swing.JTextField();
        txtSubtempacado = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtCantOriginal = new javax.swing.JTextField();
        txtValorOriginal = new javax.swing.JTextField();
        txtSubtoriginal = new javax.swing.JTextField();
        txtCantCopia = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtValorCopia = new javax.swing.JTextField();
        txtSubtcopia = new javax.swing.JTextField();
        txtCantManila = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtValorManila = new javax.swing.JTextField();
        txtSubtmanila = new javax.swing.JTextField();
        txtCantCorte = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtValorCorte = new javax.swing.JTextField();
        txtSubtcorte = new javax.swing.JTextField();
        cbxPreprensa = new javax.swing.JComboBox();
        txtCantPreprensa = new javax.swing.JTextField();
        txtValorPreprensa = new javax.swing.JTextField();
        txtSubtpreprensa = new javax.swing.JTextField();
        cbxPlancha = new javax.swing.JComboBox();
        txtCantPlancha = new javax.swing.JTextField();
        txtValorPlancha = new javax.swing.JTextField();
        txtSubtplancha = new javax.swing.JTextField();
        cbxImpresion = new javax.swing.JComboBox();
        txtCantImpresion = new javax.swing.JTextField();
        txtValorImpresion = new javax.swing.JTextField();
        txtSubtimpresion = new javax.swing.JTextField();
        txtCantNumero = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtValorNumero = new javax.swing.JTextField();
        txtSubtnumero = new javax.swing.JTextField();
        txtCantGrafado = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtValorGrafado = new javax.swing.JTextField();
        txtSubtgrafado = new javax.swing.JTextField();
        txtCantTroquel = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtValorTroquel = new javax.swing.JTextField();
        txtSubttroquel = new javax.swing.JTextField();
        txtCantRepujado = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtValorRepujado = new javax.swing.JTextField();
        txtSubtrepujado = new javax.swing.JTextField();
        txtCantRealzado = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtValorRealzado = new javax.swing.JTextField();
        txtSubtrealzado = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(31, 73, 125));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO COTIZACIÓN                                                                                                                                            S I O S");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("* Número Documento:");

        txtNombre_Cliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtNombre_Cliente.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nombre Trabajo: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Número Cotización:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Teléfono:");

        txtTelefono.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtTelefono.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Fecha Cotización:");

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.jpg"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(txtNombre_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(txtNomb_Trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroCotiza, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNumero_Identifica, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jdateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtNumero_Identifica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jdateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(txtNomb_Trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(txtNumeroCotiza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnGrabar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.jpg"))); // NOI18N
        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnRegreso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salida3.jpg"))); // NOI18N
        btnRegreso.setText("Regreso");
        btnRegreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresoActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar2.jpg"))); // NOI18N
        jButton2.setText("Cancelar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnGrabar)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(btnRegreso)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGrabar)
                    .addComponent(jButton2)
                    .addComponent(btnRegreso))
                .addContainerGap())
        );

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setText("CANTIDAD");

        jLabel9.setText("ITEM");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel10.setText("VALOR UNIDAD");

        jLabel11.setText("SUB TOTAL");

        jLabel13.setText("Estampado");

        txtCantEstampado.setText("34");

        txtValorEstampado.setText("3");
        txtValorEstampado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorEstampadoKeyReleased(evt);
            }
        });

        txtSubtestampado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSubtestampado.setEnabled(false);

        txtCantCosido.setText("34");

        jLabel14.setText("Cosido");

        txtValorCosido.setText("43");
        txtValorCosido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorCosidoKeyReleased(evt);
            }
        });

        txtSubtcosido.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSubtcosido.setEnabled(false);

        txtCantEmblocado.setText("2");

        jLabel15.setText("Emblocado");

        txtValorEmblocado.setText("7");
        txtValorEmblocado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorEmblocadoKeyReleased(evt);
            }
        });

        txtSubtemblocado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSubtemblocado.setEnabled(false);

        txtCantTransporte.setText("76");

        jLabel16.setText("Transporte");

        txtValorTransporte.setText("76");
        txtValorTransporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorTransporteKeyReleased(evt);
            }
        });

        txtSubttransporte.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSubttransporte.setEnabled(false);

        txtCantOtros.setText("6");

        txtCantTerminado.setText("4");

        cbxTerminado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Terminado", "Mate", "Brillo", "Mate con Reserva" }));

        txtValorTerminado.setText("45");
        txtValorTerminado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorTerminadoKeyReleased(evt);
            }
        });

        jLabel17.setText("Otros");

        txtValorOtros.setText("4");
        txtValorOtros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorOtrosKeyReleased(evt);
            }
        });

        txtSubtotros.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSubtotros.setEnabled(false);

        txtSubtterminado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSubtterminado.setEnabled(false);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("% Utilidad:");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setText("Valor Utilidad:");
        jPanel3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, 20));

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel38.setText("Sub Total:");
        jPanel3.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel39.setText("Valor Trabajo:");
        jPanel3.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 90, -1));

        txtUtilidad.setText("3.5");
        jPanel3.add(txtUtilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 40, -1));

        txtSubtotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSubtotal.setEnabled(false);
        jPanel3.add(txtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 71, -1));

        txtValorUtilidad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtValorUtilidad.setEnabled(false);
        jPanel3.add(txtValorUtilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 110, -1));

        txtValorTrabajo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtValorTrabajo.setEnabled(false);
        jPanel3.add(txtValorTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 110, -1));

        txtCantPlegado.setText("3");

        jLabel18.setText("Plegado");

        txtValorPlegado.setText("43");
        txtValorPlegado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorPlegadoKeyReleased(evt);
            }
        });

        txtSubtplegado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSubtplegado.setEnabled(false);

        txtCantEmpacado.setText("6");

        jLabel20.setText("Empacado");

        txtValorEmpacado.setText("76");
        txtValorEmpacado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorEmpacadoKeyReleased(evt);
            }
        });

        txtSubtempacado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSubtempacado.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtCantTerminado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbxTerminado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(txtCantCosido, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel14))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(txtCantEmblocado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel15))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(txtCantTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel16))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(txtCantOtros, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel17))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(txtCantPlegado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(txtCantEmpacado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel20))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(txtCantEstampado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtValorTerminado, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSubtterminado, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(txtValorEmpacado)
                            .addGap(18, 18, 18)
                            .addComponent(txtSubtempacado, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(txtValorTransporte)
                            .addGap(18, 18, 18)
                            .addComponent(txtSubttransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(txtValorEmblocado)
                            .addGap(18, 18, 18)
                            .addComponent(txtSubtemblocado, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtValorPlegado)
                                .addComponent(txtValorCosido, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtValorEstampado, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSubtcosido, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addGap(29, 29, 29)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(txtSubtestampado))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(txtSubtplegado, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addComponent(txtValorOtros)
                            .addGap(18, 18, 18)
                            .addComponent(txtSubtotros, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtCantEstampado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorEstampado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubtestampado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtCantPlegado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorPlegado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubtplegado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtCantCosido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorCosido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubtcosido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtCantEmblocado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorEmblocado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubtemblocado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtCantEmpacado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorEmpacado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubtempacado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtCantTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubttransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantOtros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtValorOtros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubtotros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCantTerminado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtValorTerminado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSubtterminado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxTerminado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
        );

        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setText("CANTIDAD");

        jLabel21.setText("ITEM");
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel22.setText("VALOR UNIDAD");

        jLabel23.setText("SUB TOTAL");

        jLabel24.setText("Papel Original");

        txtCantOriginal.setText("2");

        txtValorOriginal.setText("23");
        txtValorOriginal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorOriginalKeyReleased(evt);
            }
        });

        txtSubtoriginal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSubtoriginal.setEnabled(false);

        txtCantCopia.setText("2");

        jLabel25.setText("Papel Copia");

        txtValorCopia.setText("3");
        txtValorCopia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorCopiaKeyReleased(evt);
            }
        });

        txtSubtcopia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSubtcopia.setEnabled(false);

        txtCantManila.setText("3");

        jLabel26.setText("Manila");

        txtValorManila.setText("4");
        txtValorManila.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorManilaKeyReleased(evt);
            }
        });

        txtSubtmanila.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSubtmanila.setEnabled(false);

        txtCantCorte.setText("4");

        jLabel27.setText("Corte");

        txtValorCorte.setText("5");
        txtValorCorte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorCorteKeyReleased(evt);
            }
        });

        txtSubtcorte.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSubtcorte.setEnabled(false);

        cbxPreprensa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pre Prensa", "Arte", "Negativo", "Color Kit", "Clicet" }));

        txtCantPreprensa.setText("5");

        txtValorPreprensa.setText("5");
        txtValorPreprensa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorPreprensaKeyReleased(evt);
            }
        });

        txtSubtpreprensa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSubtpreprensa.setEnabled(false);

        cbxPlancha.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tipo Plancha", "P.Electros.", "P.Metálica" }));

        txtCantPlancha.setText("5");

        txtValorPlancha.setText("6");
        txtValorPlancha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorPlanchaKeyReleased(evt);
            }
        });

        txtSubtplancha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSubtplancha.setEnabled(false);

        cbxImpresion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tipo Impresión", "Sencilla", "Doble" }));

        txtCantImpresion.setText("6");

        txtValorImpresion.setText("7");
        txtValorImpresion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorImpresionKeyReleased(evt);
            }
        });

        txtSubtimpresion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSubtimpresion.setEnabled(false);

        txtCantNumero.setText("7");

        jLabel29.setText("Numeración");

        txtValorNumero.setText("7");
        txtValorNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorNumeroKeyReleased(evt);
            }
        });

        txtSubtnumero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSubtnumero.setEnabled(false);

        txtCantGrafado.setText("8");

        jLabel30.setText("Grafado");

        txtValorGrafado.setText("8");
        txtValorGrafado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorGrafadoKeyReleased(evt);
            }
        });

        txtSubtgrafado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSubtgrafado.setEnabled(false);

        txtCantTroquel.setText("4");

        jLabel31.setText("Troquelado");

        txtValorTroquel.setText("43");
        txtValorTroquel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorTroquelKeyReleased(evt);
            }
        });

        txtSubttroquel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSubttroquel.setEnabled(false);

        txtCantRepujado.setText("3");

        jLabel32.setText("Repujado");

        txtValorRepujado.setText("43");
        txtValorRepujado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorRepujadoKeyReleased(evt);
            }
        });

        txtSubtrepujado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSubtrepujado.setEnabled(false);

        txtCantRealzado.setText("4");

        jLabel33.setText("Realzado");

        txtValorRealzado.setText("43");
        txtValorRealzado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorRealzadoKeyReleased(evt);
            }
        });

        txtSubtrealzado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSubtrealzado.setEnabled(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addComponent(txtCantPlancha, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxPlancha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(txtCantOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(txtCantCopia, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel25))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(txtCantManila, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel26))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(txtCantCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel27))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(txtCantPreprensa, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxPreprensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtValorPreprensa, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSubtpreprensa, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(txtValorCorte)
                            .addGap(18, 18, 18)
                            .addComponent(txtSubtcorte, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(txtValorManila)
                            .addGap(18, 18, 18)
                            .addComponent(txtSubtmanila, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtValorCopia)
                                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtValorOriginal))
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(txtSubtcopia, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSubtoriginal))))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtValorPlancha, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSubtplancha, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtCantImpresion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxImpresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtCantNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel29))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtCantGrafado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel30))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtCantTroquel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel31))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtCantRepujado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel32))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtCantRealzado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel33)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtValorRealzado)
                        .addGap(18, 18, 18)
                        .addComponent(txtSubtrealzado, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtValorRepujado)
                        .addGap(18, 18, 18)
                        .addComponent(txtSubtrepujado, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtValorTroquel)
                        .addGap(18, 18, 18)
                        .addComponent(txtSubttroquel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtValorGrafado)
                        .addGap(18, 18, 18)
                        .addComponent(txtSubtgrafado, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtValorNumero)
                        .addGap(18, 18, 18)
                        .addComponent(txtSubtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtValorImpresion, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSubtimpresion, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addGap(9, 9, 9)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtCantOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubtoriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtCantCopia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorCopia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubtcopia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtCantManila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorManila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubtmanila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtCantCorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorCorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubtcorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxPreprensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantPreprensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorPreprensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubtpreprensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxPlancha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantPlancha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorPlancha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubtplancha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantImpresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorImpresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubtimpresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxImpresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txtCantNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txtCantGrafado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorGrafado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubtgrafado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtCantTroquel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorTroquel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubttroquel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txtCantRepujado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorRepujado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubtrepujado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(txtCantRealzado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorRealzado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubtrealzado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("* Campos obligatorios");
        jLabel19.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(64, 64, 64)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresoActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            idcliente = Integer.parseInt(txtNumero_Identifica.getText());
            ResultSet rs = objClienteCtl.buscar_clienteCtl(idcliente);
            if (rs != null) {
                rs.next();
                this.txtNombre_Cliente.setText(rs.getString(2));
                this.txtTelefono.setText(rs.getString(4));
                this.txtNumero_Identifica.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(null, "Cliente no existe");
                this.txtNumero_Identifica.requestFocus();
                this.txtNumero_Identifica.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Cliente no existe");
            this.txtNumero_Identifica.requestFocus();
            this.txtNumero_Identifica.setText("");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        String trabajo, preprensa, plancha, impresion, terminado, rs;
        Date fecha;
        int cant_p_orig, val_p_orig, cant_p_copia, val_p_copia, cant_manila, val_manila, cant_corte, val_corte, cant_preprensa, val_preprensa;
        int cant_plancha, val_plancha, cant_impresion, val_impresion, cant_numeracion, val_numeracion, cant_grafado, val_grafado, cant_troquel, val_troquel;
        int cant_repujado, val_repujado, cant_realzado, val_realzado, cant_estampado, val_estampado, cant_plegado, val_plegado, cant_cosido, val_cosido;
        int cant_emblocado, val_emblocado, cant_empacado, val_empacado, cant_trans, val_trans, cant_otros, val_otros, cant_terminado, val_terminado, estado=1, subtotal;
        double utilidad=0;
        //idcotizacion = Integer.parseInt(txtNumero_Identifica.getText());
        trabajo = txtNomb_Trabajo.getText().toUpperCase();
        fecha=jdateFecha.getDate().toString();
        cant_p_orig = Integer.parseInt(txtCantOriginal.getText());
        val_p_orig = Integer.parseInt(txtValorOriginal.getText());
        cant_p_copia = Integer.parseInt(txtCantCopia.getText());
        val_p_copia = Integer.parseInt(txtValorCopia.getText());
        cant_manila = Integer.parseInt(txtCantManila.getText());
        val_manila = Integer.parseInt(txtValorManila.getText());
        cant_corte = Integer.parseInt(txtCantCorte.getText());
        val_corte = Integer.parseInt(txtValorCorte.getText());
        cant_preprensa = Integer.parseInt(txtCantPreprensa.getText());
        preprensa = cbxPreprensa.getSelectedItem().toString();
        val_preprensa = Integer.parseInt(txtValorPreprensa.getText());
        cant_plancha = Integer.parseInt(txtCantPlancha.getText());
        plancha = cbxPlancha.getSelectedItem().toString();
        val_plancha = Integer.parseInt(txtValorPlancha.getText());
        cant_impresion = Integer.parseInt(txtCantImpresion.getText());
        impresion = cbxImpresion.getSelectedItem().toString();
        val_impresion = Integer.parseInt(txtValorImpresion.getText());
        cant_numeracion = Integer.parseInt(txtCantNumero.getText());
        val_numeracion = Integer.parseInt(txtValorNumero.getText());
        cant_grafado = Integer.parseInt(txtCantGrafado.getText());
        val_grafado = Integer.parseInt(txtValorGrafado.getText());
        cant_troquel = Integer.parseInt(txtCantTroquel.getText());
        val_troquel = Integer.parseInt(txtValorTroquel.getText());
        cant_repujado = Integer.parseInt(txtCantRepujado.getText());
        val_repujado = Integer.parseInt(txtValorRepujado.getText());
        cant_realzado = Integer.parseInt(txtCantRealzado.getText());
        val_realzado = Integer.parseInt(txtValorRealzado.getText());
        cant_estampado = Integer.parseInt(txtCantEstampado.getText());
        val_estampado = Integer.parseInt(txtValorEstampado.getText());
        cant_plegado = Integer.parseInt(txtCantPlegado.getText());
        val_plegado = Integer.parseInt(txtValorPlegado.getText());
        cant_cosido = Integer.parseInt(txtCantCosido.getText());
        val_cosido = Integer.parseInt(txtValorCosido.getText());    
        cant_emblocado = Integer.parseInt(txtCantEmblocado.getText());
        val_emblocado = Integer.parseInt(txtValorEmblocado.getText());
        cant_empacado = Integer.parseInt(txtCantEmpacado.getText());
        val_empacado = Integer.parseInt(txtValorEmpacado.getText());
        cant_trans = Integer.parseInt(txtCantTransporte.getText());
        val_trans = Integer.parseInt(txtValorTransporte.getText());
        cant_otros = Integer.parseInt(txtCantOtros.getText());
        val_otros = Integer.parseInt(txtValorOtros.getText());
        cant_terminado = Integer.parseInt(txtCantTerminado.getText());
        terminado = cbxTerminado.getSelectedItem().toString();
        val_terminado = Integer.parseInt(txtValorTerminado.getText());
        utilidad=Double.parseDouble(txtUtilidad.getText());
        rs=objCotizacionCtl.registrar_cotizacionCtl(idcliente, trabajo,fecha,cant_p_orig, val_p_orig, cant_p_copia, val_p_copia, 
                  cant_manila,val_manila, cant_corte, val_corte, preprensa, cant_preprensa, val_preprensa, plancha, cant_plancha, val_plancha,
                  impresion, cant_impresion, val_impresion, cant_numeracion, val_numeracion, cant_grafado, val_grafado, cant_troquel, val_troquel,
                  cant_repujado, val_repujado, cant_realzado, val_realzado,cant_estampado, val_estampado, cant_plegado, val_plegado, cant_cosido, val_cosido,
                  cant_emblocado, val_emblocado, cant_empacado, val_empacado, cant_trans, val_trans, cant_otros, val_otros, terminado, cant_terminado, val_terminado,
                  utilidad, estado);

        //JOptionPane.showMessageDialog(this, rs);
//        limpiarcliente();



    }//GEN-LAST:event_btnGrabarActionPerformed

    private void txtValorOriginalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorOriginalKeyReleased
        int st=0;
        try{
        st=Integer.parseInt(txtCantOriginal.getText())*Integer.parseInt(txtValorOriginal.getText());
        }
        catch(Exception ex){}
        txtSubtoriginal.setText(String.valueOf(st));
        //        if(txtSubtoriginal.getText()!=(null)){
//            int st;
//            st=Integer.parseInt(txtCantOriginal.getText())*Integer.parseInt(txtValorOriginal.getText());
//            this.txtSubtoriginal.setText(String.valueOf(st));
//        }else  {
//             this.txtSubtoriginal.setText("");
//        }
    }//GEN-LAST:event_txtValorOriginalKeyReleased

    private void txtValorCopiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorCopiaKeyReleased
        int st=0;
        try{
        st=Integer.parseInt(txtCantCopia.getText())*Integer.parseInt(txtValorCopia.getText());
        }
        catch(Exception ex){}
        txtSubtcopia.setText(String.valueOf(st));
        
    }//GEN-LAST:event_txtValorCopiaKeyReleased

    private void txtValorManilaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorManilaKeyReleased
       int st=0;
        try{
        st=Integer.parseInt(txtCantManila.getText())*Integer.parseInt(txtValorManila.getText());
        }
        catch(Exception ex){}
        txtSubtmanila.setText(String.valueOf(st));
    }//GEN-LAST:event_txtValorManilaKeyReleased

    private void txtValorCorteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorCorteKeyReleased
        int st=0;
        try{
        st=Integer.parseInt(txtCantCorte.getText())*Integer.parseInt(txtValorCorte.getText());
        }
        catch(Exception ex){}
        txtSubtcorte.setText(String.valueOf(st));
    }//GEN-LAST:event_txtValorCorteKeyReleased

    private void txtValorPreprensaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorPreprensaKeyReleased
        int st=0;
        try{
        st=Integer.parseInt(txtCantPreprensa.getText())*Integer.parseInt(txtValorPreprensa.getText());
        }
        catch(Exception ex){}
        txtSubtpreprensa.setText(String.valueOf(st));
    }//GEN-LAST:event_txtValorPreprensaKeyReleased

    private void txtValorPlanchaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorPlanchaKeyReleased
        int st=0;
        try{
        st=Integer.parseInt(txtCantPlancha.getText())*Integer.parseInt(txtValorPlancha.getText());
        }
        catch(Exception ex){}
        txtSubtplancha.setText(String.valueOf(st));
    }//GEN-LAST:event_txtValorPlanchaKeyReleased

    private void txtValorImpresionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorImpresionKeyReleased
        int st=0;
        try{
        st=Integer.parseInt(txtCantImpresion.getText())*Integer.parseInt(txtValorImpresion.getText());
        }
        catch(Exception ex){}
        txtSubtimpresion.setText(String.valueOf(st));
    }//GEN-LAST:event_txtValorImpresionKeyReleased

    private void txtValorNumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorNumeroKeyReleased
        int st=0;
        try{
        st=Integer.parseInt(txtCantNumero.getText())*Integer.parseInt(txtValorNumero.getText());
        }
        catch(Exception ex){}
        txtSubtnumero.setText(String.valueOf(st));
    }//GEN-LAST:event_txtValorNumeroKeyReleased

    private void txtValorGrafadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorGrafadoKeyReleased
    int st=0;
        try{
        st=Integer.parseInt(txtCantGrafado.getText())*Integer.parseInt(txtValorGrafado.getText());
        }
        catch(Exception ex){}
        txtSubtgrafado.setText(String.valueOf(st));
    }//GEN-LAST:event_txtValorGrafadoKeyReleased

    private void txtValorTroquelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorTroquelKeyReleased
        int st=0;
        try{
        st=Integer.parseInt(txtCantTroquel.getText())*Integer.parseInt(txtValorTroquel.getText());
        }
        catch(Exception ex){}
        txtSubttroquel.setText(String.valueOf(st));
    }//GEN-LAST:event_txtValorTroquelKeyReleased

    private void txtValorRepujadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorRepujadoKeyReleased
        int st=0;
        try{
        st=Integer.parseInt(txtCantRepujado.getText())*Integer.parseInt(txtValorRepujado.getText());
        }
        catch(Exception ex){}
        txtSubtrepujado.setText(String.valueOf(st));
    }//GEN-LAST:event_txtValorRepujadoKeyReleased

    private void txtValorRealzadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorRealzadoKeyReleased
        int st=0;
        try{
        st=Integer.parseInt(txtCantRealzado.getText())*Integer.parseInt(txtValorRealzado.getText());
        }
        catch(Exception ex){}
        txtSubtrealzado.setText(String.valueOf(st));
    }//GEN-LAST:event_txtValorRealzadoKeyReleased

    private void txtValorEstampadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorEstampadoKeyReleased
        int st=0;
        try{
        st=Integer.parseInt(txtCantEstampado.getText())*Integer.parseInt(txtValorEstampado.getText());
        }
        catch(Exception ex){}
        txtSubtestampado.setText(String.valueOf(st));
    }//GEN-LAST:event_txtValorEstampadoKeyReleased

    private void txtValorPlegadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorPlegadoKeyReleased
        int st=0;
        try{
        st=Integer.parseInt(txtCantPlegado.getText())*Integer.parseInt(txtValorPlegado.getText());
        }
        catch(Exception ex){}
        txtSubtplegado.setText(String.valueOf(st));
    }//GEN-LAST:event_txtValorPlegadoKeyReleased

    private void txtValorCosidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorCosidoKeyReleased
        int st=0;
        try{
        st=Integer.parseInt(txtCantCosido.getText())*Integer.parseInt(txtValorCosido.getText());
        }
        catch(Exception ex){}
        txtSubtcosido.setText(String.valueOf(st));
    }//GEN-LAST:event_txtValorCosidoKeyReleased

    private void txtValorEmblocadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorEmblocadoKeyReleased
        int st=0;
        try{
        st=Integer.parseInt(txtCantEmblocado.getText())*Integer.parseInt(txtValorEmblocado.getText());
        }
        catch(Exception ex){}
        txtSubtemblocado.setText(String.valueOf(st));
    }//GEN-LAST:event_txtValorEmblocadoKeyReleased

    private void txtValorEmpacadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorEmpacadoKeyReleased
        int st=0;
        try{
        st=Integer.parseInt(txtCantEmpacado.getText())*Integer.parseInt(txtValorEmpacado.getText());
        }
        catch(Exception ex){}
        txtSubtempacado.setText(String.valueOf(st));
    }//GEN-LAST:event_txtValorEmpacadoKeyReleased

    private void txtValorTransporteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorTransporteKeyReleased
        int st=0;
        try{
        st=Integer.parseInt(txtCantTransporte.getText())*Integer.parseInt(txtValorTransporte.getText());
        }
        catch(Exception ex){}
        txtSubttransporte.setText(String.valueOf(st));
    }//GEN-LAST:event_txtValorTransporteKeyReleased

    private void txtValorOtrosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorOtrosKeyReleased
        int st=0;
        try{
        st=Integer.parseInt(txtCantOtros.getText())*Integer.parseInt(txtValorOtros.getText());
        }
        catch(Exception ex){}
        txtSubtotros.setText(String.valueOf(st));
    }//GEN-LAST:event_txtValorOtrosKeyReleased

    private void txtValorTerminadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorTerminadoKeyReleased
        int st=0;
        try{
        st=Integer.parseInt(txtCantTerminado.getText())*Integer.parseInt(txtValorTerminado.getText());
        }
        catch(Exception ex){}
        txtSubtterminado.setText(String.valueOf(st));
    }//GEN-LAST:event_txtValorTerminadoKeyReleased
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDRegistrar_Cotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDRegistrar_Cotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDRegistrar_Cotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDRegistrar_Cotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {


                JDRegistrar_Cotizacion dialog = new JDRegistrar_Cotizacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnRegreso;
    private javax.swing.JComboBox cbxImpresion;
    private javax.swing.JComboBox cbxPlancha;
    private javax.swing.JComboBox cbxPreprensa;
    private javax.swing.JComboBox cbxTerminado;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private com.toedter.calendar.JDateChooser jdateFecha;
    private javax.swing.JTextField txtCantCopia;
    private javax.swing.JTextField txtCantCorte;
    private javax.swing.JTextField txtCantCosido;
    private javax.swing.JTextField txtCantEmblocado;
    private javax.swing.JTextField txtCantEmpacado;
    private javax.swing.JTextField txtCantEstampado;
    private javax.swing.JTextField txtCantGrafado;
    private javax.swing.JTextField txtCantImpresion;
    private javax.swing.JTextField txtCantManila;
    private javax.swing.JTextField txtCantNumero;
    private javax.swing.JTextField txtCantOriginal;
    private javax.swing.JTextField txtCantOtros;
    private javax.swing.JTextField txtCantPlancha;
    private javax.swing.JTextField txtCantPlegado;
    private javax.swing.JTextField txtCantPreprensa;
    private javax.swing.JTextField txtCantRealzado;
    private javax.swing.JTextField txtCantRepujado;
    private javax.swing.JTextField txtCantTerminado;
    private javax.swing.JTextField txtCantTransporte;
    private javax.swing.JTextField txtCantTroquel;
    private javax.swing.JTextField txtNomb_Trabajo;
    private javax.swing.JTextField txtNombre_Cliente;
    private javax.swing.JTextField txtNumeroCotiza;
    private javax.swing.JTextField txtNumero_Identifica;
    private javax.swing.JTextField txtSubtcopia;
    private javax.swing.JTextField txtSubtcorte;
    private javax.swing.JTextField txtSubtcosido;
    private javax.swing.JTextField txtSubtemblocado;
    private javax.swing.JTextField txtSubtempacado;
    private javax.swing.JTextField txtSubtestampado;
    private javax.swing.JTextField txtSubtgrafado;
    private javax.swing.JTextField txtSubtimpresion;
    private javax.swing.JTextField txtSubtmanila;
    private javax.swing.JTextField txtSubtnumero;
    private javax.swing.JTextField txtSubtoriginal;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtSubtotros;
    private javax.swing.JTextField txtSubtplancha;
    private javax.swing.JTextField txtSubtplegado;
    private javax.swing.JTextField txtSubtpreprensa;
    private javax.swing.JTextField txtSubtrealzado;
    private javax.swing.JTextField txtSubtrepujado;
    private javax.swing.JTextField txtSubtterminado;
    private javax.swing.JTextField txtSubttransporte;
    private javax.swing.JTextField txtSubttroquel;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUtilidad;
    private javax.swing.JTextField txtValorCopia;
    private javax.swing.JTextField txtValorCorte;
    private javax.swing.JTextField txtValorCosido;
    private javax.swing.JTextField txtValorEmblocado;
    private javax.swing.JTextField txtValorEmpacado;
    private javax.swing.JTextField txtValorEstampado;
    private javax.swing.JTextField txtValorGrafado;
    private javax.swing.JTextField txtValorImpresion;
    private javax.swing.JTextField txtValorManila;
    private javax.swing.JTextField txtValorNumero;
    private javax.swing.JTextField txtValorOriginal;
    private javax.swing.JTextField txtValorOtros;
    private javax.swing.JTextField txtValorPlancha;
    private javax.swing.JTextField txtValorPlegado;
    private javax.swing.JTextField txtValorPreprensa;
    private javax.swing.JTextField txtValorRealzado;
    private javax.swing.JTextField txtValorRepujado;
    private javax.swing.JTextField txtValorTerminado;
    private javax.swing.JTextField txtValorTrabajo;
    private javax.swing.JTextField txtValorTransporte;
    private javax.swing.JTextField txtValorTroquel;
    private javax.swing.JTextField txtValorUtilidad;
    // End of variables declaration//GEN-END:variables
}
